namespace Pokemons 
{
	class Pokemons 
	{
		public static List<Pokemon> Population = new List<Pokemon>();
		public static List<Pokemon> PopulationFirstGen = new List<Pokemon>();
		public static List<Pokemon> PopulationSecondGen = new List<Pokemon>();
		public static List<Pokemon> PopulationThirdGen = new List<Pokemon>();
		public static IDictionary<string, ConsoleColor> EnergytypeAndColors = new Dictionary<string, ConsoleColor>
		{
			{"Normal", ConsoleColor.White},
			{"Fire", ConsoleColor.Red},
			{"Water", ConsoleColor.Blue},
			{"Electric", ConsoleColor.Yellow},
			{"Grass", ConsoleColor.Green},
			{"Ice", ConsoleColor.Cyan},
			{"Fighting", ConsoleColor.DarkRed},
			{"Poison", ConsoleColor.DarkGreen},
			{"Ground", ConsoleColor.DarkGray},
			{"Flying", ConsoleColor.DarkGray},
			{"Psychic", ConsoleColor.DarkGray},
			{"Bug", ConsoleColor.DarkGray},
			{"Rock", ConsoleColor.DarkGray},
			{"Ghost", ConsoleColor.DarkGray},
			{"Dragon", ConsoleColor.DarkGray},
			{"Dark", ConsoleColor.DarkGray},
			{"Steel", ConsoleColor.DarkGray},
			{"Fairy", ConsoleColor.DarkGray}
		};
		
		public static List<Pokemon> GetPopulation()
		{
			return Population;
		}

		public static Pokemon getPokemonByName(string name)
		{
			foreach (var pokemon in Population)
			{
				if (pokemon.Name == name)
				{
					return pokemon;
				}
			}
			return null;
		}
	}
	class Pokemon : Pokemons
	{
		public string Name = "";
		public string EnergyType = "";
		public int Health;
		public int HitPoints;
		public IDictionary<string, int> Attacks = new Dictionary<string, int>();
		public IDictionary<string, int> Weakness = new Dictionary<string, int>();
		public IDictionary<string, int> Resistance = new Dictionary<string, int>();

		public Pokemon(string name, string energyType, int health, int hitPoints, IDictionary<string, int> attacks, IDictionary<string, int> weakness, IDictionary<string, int> resistance)
		{
			this.Name = name;
			this.EnergyType = energyType;
			this.Health = health;
			this.HitPoints = health;
			this.Attacks = attacks;
			this.Weakness = weakness;
			this.Resistance = resistance;

			Pokemon.Population.Add(this); // de HELE populatie
		}
		
	}

	class Init
	{
		public static void InitializePokemons()
		{
			//Console.WriteLine("Initializing Pokemons...");
			//gen1
			Pokemon Bulbasaur = new Pokemon ("Bulbasaur", "Grass", 45, 45, new Dictionary<string, int> { { "Tackle", 35 }, { "Power Whip", 10}, { "Vine Whip", 25 } }, new Dictionary<string, int> { { "Fire", 2 }, { "Grass", 0.5 } }, new Dictionary<string, int> { { "Fire", 0.5 }, { "Grass", 2 } });
			Pokemon Ivysaur = new Pokemon ("Ivysaur", "Grass", 60, 60, new Dictionary<string, int> { { "Bullet Seed", 30 }, { "Razor Leaf", 25}, { "Vine Whip", 25 } }, new Dictionary<string, int> { { "Fire", 2 }, { "Grass", 0.5 } }, new Dictionary<string, int> { { "Fire", 0.5 }, { "Grass", 2 } });
			Pokemon Venusaur = new Pokemon ("Venusaur", "Grass", 80, 80, new Dictionary<string, int> { { "Bullet Seed", 30 }, { "Razor Leaf", 25}, { "Vine Whip", 25 } }, new Dictionary<string, int> { { "Fire", 2 }, { "Grass", 0.5 } }, new Dictionary<string, int> { { "Fire", 0.5 }, { "Grass", 2 } });
			Pokemon Charmander = new Pokemon ("Charmander", "Fire", 39, 39, new Dictionary<string, int> { { "Scratch", 35 }, { "Ember", 10}, { "Fire Spin", 25 } }, new Dictionary<string, int> { { "Water", 2 }, { "Fire", 0.5 } }, new Dictionary<string, int> { { "Water", 0.5 }, { "Fire", 2 } });
			Pokemon Charmeleon = new Pokemon ("Charmeleon", "Fire", 58, 58, new Dictionary<string, int> { { "Scratch", 35 }, { "Ember", 10}, { "Fire Spin", 25 } }, new Dictionary<string, int> { { "Water", 2 }, { "Fire", 0.5 } }, new Dictionary<string, int> { { "Water", 0.5 }, { "Fire", 2 } });
			Pokemon Charizard = new Pokemon ("Charizard", "Fire", 78, 78, new Dictionary<string, int> { { "Scratch", 35 }, { "Ember", 10}, { "Fire Spin", 25 } }, new Dictionary<string, int> { { "Water", 2 }, { "Fire", 0.5 } }, new Dictionary<string, int> { { "Water", 0.5 }, { "Fire", 2 } });
			Pokemon Squirtle = new Pokemon ("Squirtle", "Water", 44, 44, new Dictionary<string, int> { { "Tackle", 35 }, { "Bubble", 10}, { "Water Gun", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Water", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Water", 2 } });
			Pokemon Wartortle = new Pokemon ("Wartortle", "Water", 59, 59, new Dictionary<string, int> { { "Tackle", 35 }, { "Bubble", 10}, { "Water Gun", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Water", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Water", 2 } });
			Pokemon Blastoise = new Pokemon ("Blastoise", "Water", 79, 79, new Dictionary<string, int> { { "Tackle", 35 }, { "Bubble", 10}, { "Water Gun", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Water", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Water", 2 } });
			Pokemon Caterpie = new Pokemon ("Caterpie", "Bug", 45, 45, new Dictionary<string, int> { { "Tackle", 35 }, { "String Shot", 10}, { "Struggle", 25 } }, new Dictionary<string, int> { { "Fire", 2 }, { "Grass", 0.5 } }, new Dictionary<string, int> { { "Fire", 0.5 }, { "Grass", 2 } });
			Pokemon Metapod = new Pokemon ("Metapod", "Bug", 50, 50, new Dictionary<string, int> { { "Tackle", 35 }, { "String Shot", 10}, { "Struggle", 25 } }, new Dictionary<string, int> { { "Fire", 2 }, { "Grass", 0.5 } }, new Dictionary<string, int> { { "Fire", 0.5 }, { "Grass", 2 } });
			Pokemon Butterfree = new Pokemon ("Butterfree", "Bug", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "String Shot", 10}, { "Struggle", 25 } }, new Dictionary<string, int> { { "Fire", 2 }, { "Grass", 0.5 } }, new Dictionary<string, int> { { "Fire", 0.5 }, { "Grass", 2 } });
			Pokemon Weedle = new Pokemon ("Weedle", "Bug", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "String Shot", 10}, { "Struggle", 25 } }, new Dictionary<string, int> { { "Fire", 2 }, { "Grass", 0.5 } }, new Dictionary<string, int> { { "Fire", 0.5 }, { "Grass", 2 } });
			Pokemon Kakuna = new Pokemon ("Kakuna", "Bug", 50, 50, new Dictionary<string, int> { { "Tackle", 35 }, { "String Shot", 10}, { "Struggle", 25 } }, new Dictionary<string, int> { { "Fire", 2 }, { "Grass", 0.5 } }, new Dictionary<string, int> { { "Fire", 0.5 }, { "Grass", 2 } });
			Pokemon Beedrill = new Pokemon ("Beedrill", "Bug", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "String Shot", 10}, { "Struggle", 25 } }, new Dictionary<string, int> { { "Fire", 2 }, { "Grass", 0.5 } }, new Dictionary<string, int> { { "Fire", 0.5 }, { "Grass", 2 } });
			Pokemon Pidgey = new Pokemon ("Pidgey", "Normal", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Gust", 10}, { "Quick Attack", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Pidgeotto = new Pokemon ("Pidgeotto", "Normal", 63, 63, new Dictionary<string, int> { { "Tackle", 35 }, { "Gust", 10}, { "Quick Attack", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Pidgeot = new Pokemon ("Pidgeot", "Normal", 83, 83, new Dictionary<string, int> { { "Tackle", 35 }, { "Gust", 10}, { "Quick Attack", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Rattata = new Pokemon ("Rattata", "Normal", 30, 30, new Dictionary<string, int> { { "Tackle", 35 }, { "Quick Attack", 10}, { "Hyper Fang", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Raticate = new Pokemon ("Raticate", "Normal", 55, 55, new Dictionary<string, int> { { "Tackle", 35 }, { "Quick Attack", 10}, { "Hyper Fang", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Spearow = new Pokemon ("Spearow", "Normal", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Peck", 10}, { "Drill Peck", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Fearow = new Pokemon ("Fearow", "Normal", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Peck", 10}, { "Drill Peck", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Ekans = new Pokemon ("Ekans", "Poison", 35, 35, new Dictionary<string, int> { { "Tackle", 35 }, { "Poison Sting", 10}, { "Wrap", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Arbok = new Pokemon ("Arbok", "Poison", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Poison Sting", 10}, { "Wrap", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } }); 
			Pokemon Pikachu = new Pokemon ("Pikachu", "Electric", 35, 35, new Dictionary<string, int> { { "Tackle", 35 }, { "Quick Attack", 10}, { "Thunder Shock", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Raichu = new Pokemon ("Raichu", "Electric", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Quick Attack", 10}, { "Thunder Shock", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Sandshrew = new Pokemon ("Sandshrew", "Ground", 50, 50, new Dictionary<string, int> { { "Tackle", 35 }, { "Scratch", 10}, { "Dig", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Sandslash = new Pokemon ("Sandslash", "Ground", 75, 75, new Dictionary<string, int> { { "Tackle", 35 }, { "Scratch", 10}, { "Dig", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon NidoranF = new Pokemon ("Nidoran♀", "Poison", 55, 55, new Dictionary<string, int> { { "Tackle", 35 }, { "Poison Sting", 10}, { "Wrap", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Nidorina = new Pokemon ("Nidorina", "Poison", 70, 70, new Dictionary<string, int> { { "Tackle", 35 }, { "Poison Sting", 10}, { "Wrap", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Nidoqueen = new Pokemon ("Nidoqueen", "Poison", 90, 90, new Dictionary<string, int> { { "Tackle", 35 }, { "Poison Sting", 10}, { "Wrap", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon NidoranM = new Pokemon ("Nidoran♂", "Poison", 46, 46, new Dictionary<string, int> { { "Tackle", 35 }, { "Poison Sting", 10}, { "Wrap", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Nidorino = new Pokemon ("Nidorino", "Poison", 61, 61, new Dictionary<string, int> { { "Tackle", 35 }, { "Poison Sting", 10}, { "Wrap", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Nidoking = new Pokemon ("Nidoking", "Poison", 81, 81, new Dictionary<string, int> { { "Tackle", 35 }, { "Poison Sting", 10}, { "Wrap", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Clefairy = new Pokemon ("Clefairy", "Normal", 70, 70, new Dictionary<string, int> { { "Tackle", 35 }, { "Quick Attack", 10}, { "Hyper Fang", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Clefable = new Pokemon ("Clefable", "Normal", 95, 95, new Dictionary<string, int> { { "Tackle", 35 }, { "Quick Attack", 10}, { "Hyper Fang", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Vulpix = new Pokemon ("Vulpix", "Fire", 38, 38, new Dictionary<string, int> { { "Tackle", 35 }, { "Ember", 10}, { "Fire Spin", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Ninetales = new Pokemon ("Ninetales", "Fire", 73, 73, new Dictionary<string, int> { { "Tackle", 35 }, { "Ember", 10}, { "Fire Spin", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Jigglypuff = new Pokemon ("Jigglypuff", "Normal", 115, 115, new Dictionary<string, int> { { "Tackle", 35 }, { "Quick Attack", 10}, { "Hyper Fang", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Wigglytuff = new Pokemon ("Wigglytuff", "Normal", 140, 140, new Dictionary<string, int> { { "Tackle", 35 }, { "Quick Attack", 10}, { "Hyper Fang", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Zubat = new Pokemon ("Zubat", "Poison", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Quick Attack", 10}, { "Hyper Fang", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Golbat = new Pokemon ("Golbat", "Poison", 75, 75, new Dictionary<string, int> { { "Tackle", 35 }, { "Quick Attack", 10}, { "Hyper Fang", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Oddish = new Pokemon ("Oddish", "Grass", 45, 45, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Gloom = new Pokemon ("Gloom", "Grass", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Vileplume = new Pokemon ("Vileplume", "Grass", 75, 75, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Paras = new Pokemon ("Paras", "Bug", 35, 35, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Parasect = new Pokemon ("Parasect", "Bug", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Venonat = new Pokemon ("Venonat", "Bug", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Venomoth = new Pokemon ("Venomoth", "Bug", 75, 75, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Diglett = new Pokemon ("Diglett", "Ground", 55, 55, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Dugtrio = new Pokemon ("Dugtrio", "Ground", 80, 80, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Meowth = new Pokemon ("Meowth", "Normal", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Persian = new Pokemon ("Persian", "Normal", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Psyduck = new Pokemon ("Psyduck", "Water", 50, 50, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Golduck = new Pokemon ("Golduck", "Water", 80, 80, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Mankey = new Pokemon ("Mankey", "Fighting", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Primeape = new Pokemon ("Primeape", "Fighting", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Growlithe = new Pokemon ("Growlithe", "Fire", 55, 55, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Arcanine = new Pokemon ("Arcanine", "Fire", 90, 90, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Poliwag = new Pokemon ("Poliwag", "Water", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Poliwhirl = new Pokemon ("Poliwhirl", "Water", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Poliwrath = new Pokemon ("Poliwrath", "Water", 90, 90, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Abra = new Pokemon ("Abra", "Psychic", 25, 25, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Kadabra = new Pokemon ("Kadabra", "Psychic", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Alakazam = new Pokemon ("Alakazam", "Psychic", 55, 55, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Machop = new Pokemon ("Machop", "Fighting", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Machoke = new Pokemon ("Machoke", "Fighting", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Machamp = new Pokemon ("Machamp", "Fighting", 90, 90, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Bellsprout = new Pokemon ("Bellsprout", "Grass", 50, 50, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Weepinbell = new Pokemon ("Weepinbell", "Grass", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Victreebel = new Pokemon ("Victreebel", "Grass", 90, 90, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Tentacool = new Pokemon ("Tentacool", "Water", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Tentacruel = new Pokemon ("Tentacruel", "Water", 80, 80, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Geodude = new Pokemon ("Geodude", "Rock", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } }); 
			Pokemon Graveler = new Pokemon ("Graveler", "Rock", 55, 55, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Golem = new Pokemon ("Golem", "Rock", 80, 80, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Ponyta = new Pokemon ("Ponyta", "Fire", 50, 50, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Rapidash = new Pokemon ("Rapidash", "Fire", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Slowpoke = new Pokemon ("Slowpoke", "Water", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } }); 
			Pokemon Slowbro = new Pokemon ("Slowbro", "Water", 75, 75, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Magnemite = new Pokemon ("Magnemite", "Electric", 25, 25, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } }); 
			Pokemon Magneton = new Pokemon ("Magneton", "Electric", 50, 50, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Farfetched = new Pokemon ("Farfetch’d", "Normal", 52, 52, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Doduo = new Pokemon ("Doduo", "Normal", 35, 35, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Dodrio = new Pokemon ("Dodrio", "Normal", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Seel = new Pokemon ("Seel", "Water", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Dewgong = new Pokemon ("Dewgong", "Water", 90, 90, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Grimer = new Pokemon ("Grimer", "Poison", 80, 80, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } }); 
			Pokemon Muk = new Pokemon ("Muk", "Poison", 105, 105, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
 			Pokemon Shellder = new Pokemon ("Shellder", "Water", 30, 30, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Cloyster = new Pokemon ("Cloyster", "Water", 50, 50, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Gastly = new Pokemon ("Gastly", "Ghost", 30, 30, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Haunter = new Pokemon ("Haunter", "Ghost", 45, 45, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Gengar = new Pokemon ("Gengar", "Ghost", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Onix = new Pokemon ("Onix", "Rock", 35, 35, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Drowzee = new Pokemon ("Drowzee", "Psychic", 48, 48, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Hypno = new Pokemon ("Hypno", "Psychic", 73, 73, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Krabby = new Pokemon ("Krabby", "Water", 30, 30, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Kingler = new Pokemon ("Kingler", "Water", 55, 55, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Voltorb = new Pokemon ("Voltorb", "Electric", 30, 30, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Electrode = new Pokemon ("Electrode", "Electric", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Exeggcute = new Pokemon ("Exeggcute", "Grass", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Exeggutor = new Pokemon ("Exeggutor", "Grass", 120, 120, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Cubone = new Pokemon ("Cubone", "Ground", 50, 50, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Marowak = new Pokemon ("Marowak", "Ground", 80, 80, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Hitmonlee = new Pokemon ("Hitmonlee", "Fighting", 50, 50, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Hitmonchan = new Pokemon ("Hitmonchan", "Fighting", 50, 50, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Lickitung = new Pokemon ("Lickitung", "Normal", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Koffing = new Pokemon ("Koffing", "Poison", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Weezing = new Pokemon ("Weezing", "Poison", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Rhyhorn = new Pokemon ("Rhyhorn", "Ground", 80, 80, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Rhydon = new Pokemon ("Rhydon", "Ground", 105, 105, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Chansey = new Pokemon ("Chansey", "Normal", 250, 250, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Tangela = new Pokemon ("Tangela", "Grass", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Kangaskhan = new Pokemon ("Kangaskhan", "Normal", 105, 105, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Horsea = new Pokemon ("Horsea", "Water", 30, 30, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Seadra = new Pokemon ("Seadra", "Water", 55, 55, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Goldeen = new Pokemon ("Goldeen", "Water", 45, 45, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Seaking = new Pokemon ("Seaking", "Water", 80, 80, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Staryu = new Pokemon ("Staryu", "Water", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Starmie = new Pokemon ("Starmie", "Water", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } }); 
			Pokemon MrMime = new Pokemon ("Mr. Mime", "Psychic", 80, 80, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Scyther = new Pokemon ("Scyther", "Bug", 70, 70, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Jynx = new Pokemon ("Jynx", "Psychic", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Electabuzz = new Pokemon ("Electabuzz", "Electric", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Magmar = new Pokemon ("Magmar", "Fire", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Pinsir = new Pokemon ("Pinsir", "Bug", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Tauros = new Pokemon ("Tauros", "Normal", 75, 75, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Magikarp = new Pokemon ("Magikarp", "Water", 20, 20, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Gyarados = new Pokemon ("Gyarados", "Water", 95, 95, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Lapras = new Pokemon ("Lapras", "Water", 130, 130, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Ditto = new Pokemon ("Ditto", "Normal", 40, 40, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Eevee = new Pokemon ("Eevee", "Normal", 55, 55, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Vaporeon = new Pokemon ("Vaporeon", "Water", 130, 130, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Jolteon = new Pokemon ("Jolteon", "Electric", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Flareon = new Pokemon ("Flareon", "Fire", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Porygon = new Pokemon ("Porygon", "Normal", 65, 65, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Omanyte = new Pokemon ("Omanyte", "Rock", 35, 35, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Omastar = new Pokemon ("Omastar", "Rock", 70, 70, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Kabuto = new Pokemon ("Kabuto", "Rock", 30, 30, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Kabutops = new Pokemon ("Kabutops", "Rock", 60, 60, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Aerodactyl = new Pokemon ("Aerodactyl", "Rock", 80, 80, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Snorlax = new Pokemon ("Snorlax", "Normal", 160, 160, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Articuno = new Pokemon ("Articuno", "Ice", 90, 90, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Zapdos = new Pokemon ("Zapdos", "Electric", 90, 90, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Moltres = new Pokemon ("Moltres", "Fire", 90, 90, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Dratini = new Pokemon ("Dratini", "Dragon", 30, 30, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Dragonair = new Pokemon ("Dragonair", "Dragon", 70, 70, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Dragonite = new Pokemon ("Dragonite", "Dragon", 100, 100, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Mewtwo = new Pokemon ("Mewtwo", "Psychic", 110, 110, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			Pokemon Mew = new Pokemon ("Mew", "Psychic", 100, 100, new Dictionary<string, int> { { "Tackle", 35 }, { "Absorb", 10}, { "Poison Powder", 25 } }, new Dictionary<string, int> { { "Electric", 2 }, { "Flying", 0.5 } }, new Dictionary<string, int> { { "Electric", 0.5 }, { "Flying", 2 } });
			//gen 2 
			/*
			Pokemon Chikorita = new Pokemon
			Pokemon Bayleef = new Pokemon
			Pokemon Meganium = new Pokemon
			Pokemon Cyndaquil = new Pokemon
			Pokemon Quilava = new Pokemon
			Pokemon Typhlosion = new Pokemon
			Pokemon Totodile = new Pokemon
			Pokemon Croconaw = new Pokemon
			Pokemon Feraligatr = new Pokemon
			Pokemon Sentret = new Pokemon
			Pokemon Furret = new Pokemon
			Pokemon Hoothoot = new Pokemon
			Pokemon Noctowl = new Pokemon
			Pokemon Ledyba = new Pokemon
			Pokemon Ledian = new Pokemon
			Pokemon Spinarak = new Pokemon
			Pokemon Ariados = new Pokemon
			Pokemon Crobat = new Pokemon
			Pokemon Chinchou = new Pokemon
			Pokemon Lanturn = new Pokemon
			Pokemon Pichu = new Pokemon
			Pokemon Cleffa = new Pokemon
			Pokemon Igglybuff = new Pokemon
			Pokemon Togepi = new Pokemon
			Pokemon Togetic = new Pokemon
			Pokemon Natu = new Pokemon
			Pokemon Xatu = new Pokemon
			Pokemon Mareep = new Pokemon
			Pokemon Flaaffy = new Pokemon
			Pokemon Ampharos = new Pokemon
			Pokemon Bellossom = new Pokemon
			Pokemon Marill = new Pokemon
			Pokemon Azumarill = new Pokemon
			Pokemon Sudowoodo = new Pokemon
			Pokemon Politoed = new Pokemon
			Pokemon Hoppip = new Pokemon
			Pokemon Skiploom = new Pokemon
			Pokemon Jumpluff = new Pokemon
			Pokemon Aipom = new Pokemon
			Pokemon Sunkern = new Pokemon
			Pokemon Sunflora = new Pokemon
			Pokemon Yanma = new Pokemon
			Pokemon Wooper = new Pokemon
			Pokemon Quagsire = new Pokemon
			Pokemon Espeon = new Pokemon
			Pokemon Umbreon = new Pokemon
			Pokemon Murkrow = new Pokemon
			Pokemon Slowking = new Pokemon
			Pokemon Misdreavus = new Pokemon
			Pokemon Unown = new Pokemon
			Pokemon Wobbuffet = new Pokemon
			Pokemon Girafarig = new Pokemon
			Pokemon Pineco = new Pokemon
			Pokemon Forretress = new Pokemon
			Pokemon Dunsparce = new Pokemon
			Pokemon Gligar = new Pokemon
			Pokemon Steelix = new Pokemon
			Pokemon Snubbull = new Pokemon
			Pokemon Granbull = new Pokemon
			Pokemon Qwilfish = new Pokemon
			Pokemon Scizor = new Pokemon
			Pokemon Shuckle = new Pokemon
			Pokemon Heracross = new Pokemon
			Pokemon Sneasel = new Pokemon
			Pokemon Teddiursa = new Pokemon
			Pokemon Ursaring = new Pokemon
			Pokemon Slugma = new Pokemon
			Pokemon Magcargo = new Pokemon
			Pokemon Swinub = new Pokemon
			Pokemon Piloswine = new Pokemon
			Pokemon Corsola = new Pokemon
			Pokemon Remoraid = new Pokemon
			Pokemon Octillery = new Pokemon
			Pokemon Delibird = new Pokemon
			Pokemon Mantine = new Pokemon
			Pokemon Skarmory = new Pokemon
			Pokemon Houndour = new Pokemon
			Pokemon Houndoom = new Pokemon
			Pokemon Kingdra = new Pokemon
			Pokemon Phanpy = new Pokemon
			Pokemon Donphan = new Pokemon
			Pokemon Porygon2 = new Pokemon
			Pokemon Stantler = new Pokemon
			Pokemon Smeargle = new Pokemon
			Pokemon Tyrogue = new Pokemon
			Pokemon Hitmontop = new Pokemon
			Pokemon Smoochum = new Pokemon
			Pokemon Elekid = new Pokemon
			Pokemon Magby = new Pokemon
			Pokemon Miltank = new Pokemon
			Pokemon Blissey = new Pokemon
			Pokemon Raikou = new Pokemon
			Pokemon Entei = new Pokemon
			Pokemon Suicune = new Pokemon
			Pokemon Larvitar = new Pokemon
			Pokemon Pupitar = new Pokemon
			Pokemon Tyranitar = new Pokemon
			Pokemon Lugia = new Pokemon
			Pokemon Ho-Oh = new Pokemon
			Pokemon Celebi = new Pokemon
			//gen3
			Pokemon Treecko = new Pokemon
			Pokemon Grovyle = new Pokemon
			Pokemon Sceptile = new Pokemon
			Pokemon Torchic = new Pokemon
			Pokemon Combusken = new Pokemon
			Pokemon Blaziken = new Pokemon
			Pokemon Mudkip = new Pokemon
			Pokemon Marshtomp = new Pokemon
			Pokemon Swampert = new Pokemon
			Pokemon Poochyena = new Pokemon
			Pokemon Mightyena = new Pokemon
			Pokemon Zigzagoon = new Pokemon
			Pokemon Linoone = new Pokemon
			Pokemon Wurmple = new Pokemon
			Pokemon Silcoon = new Pokemon
			Pokemon Beautifly = new Pokemon
			Pokemon Cascoon = new Pokemon
			Pokemon Dustox = new Pokemon
			Pokemon Lotad = new Pokemon
			Pokemon Lombre = new Pokemon
			Pokemon Ludicolo = new Pokemon
			Pokemon Seedot = new Pokemon
			Pokemon Nuzleaf = new Pokemon
			Pokemon Shiftry = new Pokemon
			Pokemon Taillow = new Pokemon
			Pokemon Swellow = new Pokemon
			Pokemon Wingull = new Pokemon
			Pokemon Pelipper = new Pokemon
			Pokemon Ralts = new Pokemon
			Pokemon Kirlia = new Pokemon
			Pokemon Gardevoir = new Pokemon
			Pokemon Surskit = new Pokemon
			Pokemon Masquerain = new Pokemon
			Pokemon Shroomish = new Pokemon
			Pokemon Breloom = new Pokemon
			Pokemon Slakoth = new Pokemon
			Pokemon Vigoroth = new Pokemon
			Pokemon Slaking = new Pokemon
			Pokemon Nincada = new Pokemon
			Pokemon Ninjask = new Pokemon
			Pokemon Shedinja = new Pokemon
			Pokemon Whismur = new Pokemon
			Pokemon Loudred = new Pokemon
			Pokemon Exploud = new Pokemon
			Pokemon Makuhita = new Pokemon
			Pokemon Hariyama = new Pokemon
			Pokemon Azurill = new Pokemon
			Pokemon Nosepass = new Pokemon
			Pokemon Skitty = new Pokemon
			Pokemon Delcatty = new Pokemon
			Pokemon Sableye = new Pokemon
			Pokemon Mawile = new Pokemon
			Pokemon Aron = new Pokemon
			Pokemon Lairon = new Pokemon
			Pokemon Aggron = new Pokemon
			Pokemon Meditite = new Pokemon
			Pokemon Medicham = new Pokemon
			Pokemon Electrike = new Pokemon
			Pokemon Manectric = new Pokemon
			Pokemon Plusle = new Pokemon
			Pokemon Minun = new Pokemon
			Pokemon Volbeat = new Pokemon
			Pokemon Illumise = new Pokemon
			Pokemon Roselia = new Pokemon
			Pokemon Gulpin = new Pokemon
			Pokemon Swalot = new Pokemon
			Pokemon Carvanha = new Pokemon
			Pokemon Sharpedo = new Pokemon
			Pokemon Wailmer = new Pokemon
			Pokemon Wailord = new Pokemon
			Pokemon Numel = new Pokemon
			Pokemon Camerupt = new Pokemon
			Pokemon Torkoal = new Pokemon
			Pokemon Spoink = new Pokemon
			Pokemon Grumpig = new Pokemon
			Pokemon Spinda = new Pokemon
			Pokemon Trapinch = new Pokemon
			Pokemon Vibrava = new Pokemon
			Pokemon Flygon = new Pokemon
			Pokemon Cacnea = new Pokemon
			Pokemon Cacturne = new Pokemon
			Pokemon Swablu = new Pokemon
			Pokemon Altaria = new Pokemon
			Pokemon Zangoose = new Pokemon
			Pokemon Seviper = new Pokemon
			Pokemon Lunatone = new Pokemon
			Pokemon Solrock = new Pokemon
			Pokemon Barboach = new Pokemon
			Pokemon Whiscash = new Pokemon
			Pokemon Corphish = new Pokemon
			Pokemon Crawdaunt = new Pokemon
			Pokemon Baltoy = new Pokemon
			Pokemon Claydol = new Pokemon
			Pokemon Lileep = new Pokemon
			Pokemon Cradily = new Pokemon
			Pokemon Anorith = new Pokemon
			Pokemon Armaldo = new Pokemon
			Pokemon Feebas = new Pokemon
			Pokemon Milotic = new Pokemon
			Pokemon Castform = new Pokemon
			Pokemon Kecleon = new Pokemon
			Pokemon Shuppet = new Pokemon
			Pokemon Banette = new Pokemon
			Pokemon Duskull = new Pokemon
			Pokemon Dusclops = new Pokemon
			Pokemon Tropius = new Pokemon
			Pokemon Chimecho = new Pokemon
			Pokemon Absol = new Pokemon
			Pokemon Wynaut = new Pokemon
			Pokemon Snorunt = new Pokemon
			Pokemon Glalie = new Pokemon
			Pokemon Spheal = new Pokemon
			Pokemon Sealeo = new Pokemon
			Pokemon Walrein = new Pokemon
			Pokemon Clamperl = new Pokemon
			Pokemon Huntail = new Pokemon
			Pokemon Gorebyss = new Pokemon
			Pokemon Relicanth = new Pokemon
			Pokemon Luvdisc = new Pokemon
			Pokemon Bagon = new Pokemon
			Pokemon Shelgon = new Pokemon
			Pokemon Salamence = new Pokemon
			Pokemon Beldum = new Pokemon
			Pokemon Metang = new Pokemon
			Pokemon Metagross = new Pokemon
			Pokemon Regirock = new Pokemon
			Pokemon Regice = new Pokemon
			Pokemon Registeel = new Pokemon
			Pokemon Latias = new Pokemon
			Pokemon Latios = new Pokemon
			Pokemon Kyogre = new Pokemon
			Pokemon Groudon = new Pokemon
			Pokemon Rayquaza = new Pokemon
			Pokemon Jirachi = new Pokemon
			Pokemon Deoxys = new Pokemon
			//gen 4
			Pokemon Turtwig = new Pokemon
			Pokemon Grotle = new Pokemon
			Pokemon Torterra = new Pokemon
			Pokemon Chimchar = new Pokemon
			Pokemon Monferno = new Pokemon
			Pokemon Infernape = new Pokemon
			Pokemon Piplup = new Pokemon
			Pokemon Prinplup = new Pokemon
			Pokemon Empoleon = new Pokemon
			Pokemon Starly = new Pokemon
			Pokemon Staravia = new Pokemon
			Pokemon Staraptor = new Pokemon
			Pokemon Bidoof = new Pokemon
			Pokemon Bibarel = new Pokemon
			Pokemon Kricketot = new Pokemon
			Pokemon Kricketune = new Pokemon
			Pokemon Shinx = new Pokemon
			Pokemon Luxio = new Pokemon
			Pokemon Luxray = new Pokemon
			Pokemon Budew = new Pokemon
			Pokemon Roserade = new Pokemon
			Pokemon Cranidos = new Pokemon
			Pokemon Rampardos = new Pokemon
			Pokemon Shieldon = new Pokemon
			Pokemon Bastiodon = new Pokemon
			Pokemon Burmy = new Pokemon
			Pokemon Wormadam = new Pokemon
			Pokemon Mothim = new Pokemon
			Pokemon Combee = new Pokemon
			Pokemon Vespiquen = new Pokemon
			Pokemon Pachirisu = new Pokemon
			Pokemon Buizel = new Pokemon
			Pokemon Floatzel = new Pokemon
			Pokemon Cherubi = new Pokemon
			Pokemon Cherrim = new Pokemon
			Pokemon Shellos = new Pokemon
			Pokemon Gastrodon = new Pokemon
			Pokemon Ambipom = new Pokemon
			Pokemon Drifloon = new Pokemon
			Pokemon Drifblim = new Pokemon
			Pokemon Buneary = new Pokemon
			Pokemon Lopunny = new Pokemon
			Pokemon Mismagius = new Pokemon
			Pokemon Honchkrow = new Pokemon
			Pokemon Glameow = new Pokemon
			Pokemon Purugly = new Pokemon
			Pokemon Chingling = new Pokemon
			Pokemon Stunky = new Pokemon
			Pokemon Skuntank = new Pokemon
			Pokemon Bronzor = new Pokemon
			Pokemon Bronzong = new Pokemon
			Pokemon Bonsly = new Pokemon
			Pokemon Mime Jr. = new Pokemon
			Pokemon Happiny = new Pokemon
			Pokemon Chatot = new Pokemon
			Pokemon Spiritomb = new Pokemon
			Pokemon Gible = new Pokemon
			Pokemon Gabite = new Pokemon
			Pokemon Garchomp = new Pokemon
			Pokemon Munchlax = new Pokemon
			Pokemon Riolu = new Pokemon
			Pokemon Lucario = new Pokemon
			Pokemon Hippopotas = new Pokemon
			Pokemon Hippowdon = new Pokemon
			Pokemon Skorupi = new Pokemon
			Pokemon Drapion = new Pokemon
			Pokemon Croagunk = new Pokemon
			Pokemon Toxicroak = new Pokemon
			Pokemon Carnivine = new Pokemon
			Pokemon Finneon = new Pokemon
			Pokemon Lumineon = new Pokemon
			Pokemon Mantyke = new Pokemon
			Pokemon Snover = new Pokemon
			Pokemon Abomasnow = new Pokemon
			Pokemon Weavile = new Pokemon
			Pokemon Magnezone = new Pokemon
			Pokemon Lickilicky = new Pokemon
			Pokemon Rhyperior = new Pokemon
			Pokemon Tangrowth = new Pokemon
			Pokemon Electivire = new Pokemon
			Pokemon Magmortar = new Pokemon
			Pokemon Togekiss = new Pokemon
			Pokemon Yanmega = new Pokemon
			Pokemon Leafeon = new Pokemon
			Pokemon Glaceon = new Pokemon
			Pokemon Gliscor = new Pokemon
			Pokemon Mamoswine = new Pokemon
			Pokemon Porygon-Z = new Pokemon
			Pokemon Gallade = new Pokemon
			Pokemon Probopass = new Pokemon
			Pokemon Dusknoir = new Pokemon
			Pokemon Froslass = new Pokemon
			Pokemon Rotom = new Pokemon
			Pokemon Uxie = new Pokemon
			Pokemon Mesprit = new Pokemon
			Pokemon Azelf = new Pokemon
			Pokemon Dialga = new Pokemon
			Pokemon Palkia = new Pokemon
			Pokemon Heatran = new Pokemon
			Pokemon Regigigas = new Pokemon
			Pokemon Giratina = new Pokemon
			Pokemon Cresselia = new Pokemon
			Pokemon Phione = new Pokemon
			Pokemon Manaphy = new Pokemon
			Pokemon Darkrai = new Pokemon
			Pokemon Shaymin = new Pokemon
			Pokemon Arceus = new Pokemon
			//gen5
			Pokemon Victini = new Pokemon
			Pokemon Snivy = new Pokemon
			Pokemon Servine = new Pokemon
			Pokemon Serperior = new Pokemon
			Pokemon Tepig = new Pokemon
			Pokemon Pignite = new Pokemon
			Pokemon Emboar = new Pokemon
			Pokemon Oshawott = new Pokemon
			Pokemon Dewott = new Pokemon
			Pokemon Samurott = new Pokemon
			Pokemon Patrat = new Pokemon
			Pokemon Watchog = new Pokemon
			Pokemon Lillipup = new Pokemon
			Pokemon Herdier = new Pokemon
			Pokemon Stoutland = new Pokemon
			Pokemon Purrloin = new Pokemon
			Pokemon Liepard = new Pokemon
			Pokemon Pansage = new Pokemon
			Pokemon Simisage = new Pokemon
			Pokemon Pansear = new Pokemon
			Pokemon Simisear = new Pokemon
			Pokemon Panpour = new Pokemon
			Pokemon Simipour = new Pokemon
			Pokemon Munna = new Pokemon
			Pokemon Musharna = new Pokemon
			Pokemon Pidove = new Pokemon
			Pokemon Tranquill = new Pokemon
			Pokemon Unfezant = new Pokemon
			Pokemon Blitzle = new Pokemon
			Pokemon Zebstrika = new Pokemon
			Pokemon Roggenrola = new Pokemon
			Pokemon Boldore = new Pokemon
			Pokemon Gigalith = new Pokemon
			Pokemon Woobat = new Pokemon
			Pokemon Swoobat = new Pokemon
			Pokemon Drilbur = new Pokemon
			Pokemon Excadrill = new Pokemon
			Pokemon Audino = new Pokemon
			Pokemon Timburr = new Pokemon
			Pokemon Gurdurr = new Pokemon
			Pokemon Conkeldurr = new Pokemon
			Pokemon Tympole = new Pokemon
			Pokemon Palpitoad = new Pokemon
			Pokemon Seismitoad = new Pokemon
			Pokemon Throh = new Pokemon
			Pokemon Sawk = new Pokemon
			Pokemon Sewaddle = new Pokemon
			Pokemon Swadloon = new Pokemon
			Pokemon Leavanny = new Pokemon
			Pokemon Venipede = new Pokemon
			Pokemon Whirlipede = new Pokemon
			Pokemon Scolipede = new Pokemon
			Pokemon Cottonee = new Pokemon
			Pokemon Whimsicott = new Pokemon
			Pokemon Petilil = new Pokemon
			Pokemon Lilligant = new Pokemon
			Pokemon Basculin = new Pokemon
			Pokemon Sandile = new Pokemon
			Pokemon Krokorok = new Pokemon
			Pokemon Krookodile = new Pokemon
			Pokemon Darumaka = new Pokemon
			Pokemon Darmanitan = new Pokemon
			Pokemon Maractus = new Pokemon
			Pokemon Dwebble = new Pokemon
			Pokemon Crustle = new Pokemon
			Pokemon Scraggy = new Pokemon
			Pokemon Scrafty = new Pokemon
			Pokemon Sigilyph = new Pokemon
			Pokemon Yamask = new Pokemon
			Pokemon Cofagrigus = new Pokemon
			Pokemon Tirtouga = new Pokemon
			Pokemon Carracosta = new Pokemon
			Pokemon Archen = new Pokemon
			Pokemon Archeops = new Pokemon
			Pokemon Trubbish = new Pokemon
			Pokemon Garbodor = new Pokemon
			Pokemon Zorua = new Pokemon
			Pokemon Zoroark = new Pokemon
			Pokemon Minccino = new Pokemon
			Pokemon Cinccino = new Pokemon
			Pokemon Gothita = new Pokemon
			Pokemon Gothorita = new Pokemon
			Pokemon Gothitelle = new Pokemon
			Pokemon Solosis = new Pokemon
			Pokemon Duosion = new Pokemon
			Pokemon Reuniclus = new Pokemon
			Pokemon Ducklett = new Pokemon
			Pokemon Swanna = new Pokemon
			Pokemon Vanillite = new Pokemon
			Pokemon Vanillish = new Pokemon
			Pokemon Vanilluxe = new Pokemon
			Pokemon Deerling = new Pokemon
			Pokemon Sawsbuck = new Pokemon
			Pokemon Emolga = new Pokemon
			Pokemon Karrablast = new Pokemon
			Pokemon Escavalier = new Pokemon
			Pokemon Foongus = new Pokemon
			Pokemon Amoonguss = new Pokemon
			Pokemon Frillish = new Pokemon
			Pokemon Jellicent = new Pokemon
			Pokemon Alomomola = new Pokemon
			Pokemon Joltik = new Pokemon
			Pokemon Galvantula = new Pokemon
			Pokemon Ferroseed = new Pokemon
			Pokemon Ferrothorn = new Pokemon
			Pokemon Klink = new Pokemon
			Pokemon Klang = new Pokemon
			Pokemon Klinklang = new Pokemon
			Pokemon Tynamo = new Pokemon
			Pokemon Eelektrik = new Pokemon
			Pokemon Eelektross = new Pokemon
			Pokemon Elgyem = new Pokemon
			Pokemon Beheeyem = new Pokemon
			Pokemon Litwick = new Pokemon
			Pokemon Lampent = new Pokemon
			Pokemon Chandelure = new Pokemon
			Pokemon Axew = new Pokemon
			Pokemon Fraxure = new Pokemon
			Pokemon Haxorus = new Pokemon
			Pokemon Cubchoo = new Pokemon
			Pokemon Beartic = new Pokemon
			Pokemon Cryogonal = new Pokemon
			Pokemon Shelmet = new Pokemon
			Pokemon Accelgor = new Pokemon
			Pokemon Stunfisk = new Pokemon
			Pokemon Mienfoo = new Pokemon
			Pokemon Mienshao = new Pokemon
			Pokemon Druddigon = new Pokemon
			Pokemon Golett = new Pokemon
			Pokemon Golurk = new Pokemon
			Pokemon Pawniard = new Pokemon
			Pokemon Bisharp = new Pokemon
			Pokemon Bouffalant = new Pokemon
			Pokemon Rufflet = new Pokemon
			Pokemon Braviary = new Pokemon
			Pokemon Vullaby = new Pokemon
			Pokemon Mandibuzz = new Pokemon
			Pokemon Heatmor = new Pokemon
			Pokemon Durant = new Pokemon
			Pokemon Deino = new Pokemon
			Pokemon Zweilous = new Pokemon
			Pokemon Hydreigon = new Pokemon
			Pokemon Larvesta = new Pokemon
			Pokemon Volcarona = new Pokemon
			Pokemon Cobalion = new Pokemon
			Pokemon Terrakion = new Pokemon
			Pokemon Virizion = new Pokemon
			Pokemon Tornadus = new Pokemon
			Pokemon Thundurus = new Pokemon
			Pokemon Reshiram = new Pokemon
			Pokemon Zekrom = new Pokemon
			Pokemon Landorus = new Pokemon
			Pokemon Kyurem = new Pokemon
			Pokemon Keldeo = new Pokemon
			Pokemon Meloetta = new Pokemon
			Pokemon Genesect = new Pokemon
			//gen6
			Pokemon Chespin = new Pokemon
			Pokemon Quilladin = new Pokemon
			Pokemon Chesnaught = new Pokemon
			Pokemon Fennekin = new Pokemon
			Pokemon Braixen = new Pokemon
			Pokemon Delphox = new Pokemon
			Pokemon Froakie = new Pokemon
			Pokemon Frogadier = new Pokemon
			Pokemon Greninja = new Pokemon
			Pokemon Bunnelby = new Pokemon
			Pokemon Diggersby = new Pokemon
			Pokemon Fletchling = new Pokemon
			Pokemon Fletchinder = new Pokemon
			Pokemon Talonflame = new Pokemon
			Pokemon Scatterbug = new Pokemon
			Pokemon Spewpa = new Pokemon
			Pokemon Vivillon = new Pokemon
			Pokemon Litleo = new Pokemon
			Pokemon Pyroar = new Pokemon
			Pokemon Flabébé = new Pokemon
			Pokemon Floette = new Pokemon
			Pokemon Florges = new Pokemon
			Pokemon Skiddo = new Pokemon
			Pokemon Gogoat = new Pokemon
			Pokemon Pancham = new Pokemon
			Pokemon Pangoro = new Pokemon
			Pokemon Furfrou = new Pokemon
			Pokemon Espurr = new Pokemon
			Pokemon Meowstic = new Pokemon
			Pokemon Honedge = new Pokemon
			Pokemon Doublade = new Pokemon
			Pokemon Aegislash = new Pokemon
			Pokemon Spritzee = new Pokemon
			Pokemon Aromatisse = new Pokemon
			Pokemon Swirlix = new Pokemon
			Pokemon Slurpuff = new Pokemon
			Pokemon Inkay = new Pokemon
			Pokemon Malamar = new Pokemon
			Pokemon Binacle = new Pokemon
			Pokemon Barbaracle = new Pokemon
			Pokemon Skrelp = new Pokemon
			Pokemon Dragalge = new Pokemon
			Pokemon Clauncher = new Pokemon
			Pokemon Clawitzer = new Pokemon
			Pokemon Helioptile = new Pokemon
			Pokemon Heliolisk = new Pokemon
			Pokemon Tyrunt = new Pokemon
			Pokemon Tyrantrum = new Pokemon
			Pokemon Amaura = new Pokemon
			Pokemon Aurorus = new Pokemon
			Pokemon Sylveon = new Pokemon
			Pokemon Hawlucha = new Pokemon
			Pokemon Dedenne = new Pokemon
			Pokemon Carbink = new Pokemon
			Pokemon Goomy = new Pokemon
			Pokemon Sliggoo = new Pokemon
			Pokemon Goodra = new Pokemon
			Pokemon Klefki = new Pokemon
			Pokemon Phantump = new Pokemon
			Pokemon Trevenant = new Pokemon
			Pokemon Pumpkaboo = new Pokemon
			Pokemon Gourgeist = new Pokemon
			Pokemon Bergmite = new Pokemon
			Pokemon Avalugg = new Pokemon
			Pokemon Noibat = new Pokemon
			Pokemon Noivern = new Pokemon
			Pokemon Xerneas = new Pokemon
			Pokemon Yveltal = new Pokemon
			Pokemon Zygarde = new Pokemon
			Pokemon Diancie = new Pokemon
			Pokemon Hoopa = new Pokemon
			//gen7
			Pokemon Volcanion = new Pokemon
			Pokemon Rowlet = new Pokemon
			Pokemon Dartrix = new Pokemon
			Pokemon Decidueye = new Pokemon
			Pokemon Litten = new Pokemon
			Pokemon Torracat = new Pokemon
			Pokemon Incineroar = new Pokemon
			Pokemon Popplio = new Pokemon
			Pokemon Brionne = new Pokemon
			Pokemon Primarina = new Pokemon
			Pokemon Pikipek = new Pokemon
			Pokemon Trumbeak = new Pokemon
			Pokemon Toucannon = new Pokemon
			Pokemon Yungoos = new Pokemon
			Pokemon Gumshoos = new Pokemon
			Pokemon Grubbin = new Pokemon
			Pokemon Charjabug = new Pokemon
			Pokemon Vikavolt = new Pokemon
			Pokemon Crabrawler = new Pokemon
			Pokemon Crabominable = new Pokemon
			Pokemon Oricorio = new Pokemon
			Pokemon Cutiefly = new Pokemon
			Pokemon Ribombee = new Pokemon
			Pokemon Rockruff = new Pokemon
			Pokemon Lycanroc = new Pokemon
			Pokemon Wishiwashi = new Pokemon
			Pokemon Mareanie = new Pokemon
			Pokemon Toxapex = new Pokemon
			Pokemon Mudbray = new Pokemon
			Pokemon Mudsdale = new Pokemon
			Pokemon Dewpider = new Pokemon
			Pokemon Araquanid = new Pokemon
			Pokemon Fomantis = new Pokemon
			Pokemon Lurantis = new Pokemon
			Pokemon Morelull = new Pokemon
			Pokemon Shiinotic = new Pokemon
			Pokemon Salandit = new Pokemon
			Pokemon Salazzle = new Pokemon
			Pokemon Stufful = new Pokemon
			Pokemon Bewear = new Pokemon
			Pokemon Bounsweet = new Pokemon
			Pokemon Steenee = new Pokemon
			Pokemon Tsareena = new Pokemon
			Pokemon Comfey = new Pokemon
			Pokemon Oranguru = new Pokemon
			Pokemon Passimian = new Pokemon
			Pokemon Wimpod = new Pokemon
			Pokemon Golisopod = new Pokemon
			Pokemon Sandygast = new Pokemon
			Pokemon Palossand = new Pokemon
			Pokemon Pyukumuku = new Pokemon
			Pokemon Type: Null = new Pokemon
			Pokemon Silvally = new Pokemon
			Pokemon Minior = new Pokemon
			Pokemon Komala = new Pokemon
			Pokemon Turtonator = new Pokemon
			Pokemon Togedemaru = new Pokemon
			Pokemon Mimikyu = new Pokemon
			Pokemon Bruxish = new Pokemon
			Pokemon Drampa = new Pokemon
			Pokemon Dhelmise = new Pokemon
			Pokemon Jangmo-o = new Pokemon
			Pokemon Hakamo-o = new Pokemon
			Pokemon Kommo-o = new Pokemon
			Pokemon Tapu Koko = new Pokemon
			Pokemon Tapu Lele = new Pokemon
			Pokemon Tapu Bulu = new Pokemon
			Pokemon Tapu Fini = new Pokemon
			Pokemon Cosmog = new Pokemon
			Pokemon Cosmoem = new Pokemon
			Pokemon Solgaleo = new Pokemon
			Pokemon Lunala = new Pokemon
			Pokemon Nihilego = new Pokemon
			Pokemon Buzzwole = new Pokemon
			Pokemon Pheromosa = new Pokemon
			Pokemon Xurkitree = new Pokemon
			Pokemon Celesteela = new Pokemon
			Pokemon Kartana = new Pokemon
			Pokemon Guzzlord = new Pokemon
			Pokemon Necrozma = new Pokemon
			Pokemon Magearna = new Pokemon
			Pokemon Marshadow = new Pokemon
			Pokemon Poipole  = new Pokemon
			Pokemon Naganadel  = new Pokemon
			Pokemon Stakataka  = new Pokemon
			Pokemon Blacephalon  = new Pokemon
			Pokemon Zeraora  = new Pokemon
			Pokemon Meltan  = new Pokemon
			Pokemon Melmetal = new Pokemon
			//gen8
			*/
			
			Pokemon.Population = Pokemon.Population.OrderBy(i => Guid.NewGuid()).ToList(); //shuffle de lijst -> guid is een 128 character die nooit meer gebruikt wordt
		}
	}
}